language: python
sudo: false
python:
- 2.7.11

cache:
  directories:
    - $HOME/.cache/pip
    - $HOME/.pip-accel

before_cache:
  - rm -f $HOME/.cache/pip/log/debug.log

install:
  - pip install pip-accel
  - pip-accel install -r requirements-dev.txt

script:
- flake8
# - py.test --cov -v --tb=native


notifications:
  email:
    on_success: change  # [always|never|change]
    on_failure: always  # [always|never|change]
